name: "Hello World"
description: "Greet someone and record the time"
inputs:
  DB_URL:
    description: "Connection URL for the Database"
    required: true
    default: "JDBC:<URL>"
  DB_PASSWORD:
    description: "Connection URL for the Database"
    required: true
    default: "PASSWORD"
  DB_FAMILY:
    description: "Provide the DB FAMILY name like - postgress, snowflake"
    required: true
    default: "DB_FAMILY"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.DB_URL }}
    - ${{ inputs.DB_PASSWORD}}
    - ${{ inputs.DB_FAMILY}}
