name: "Hello World"
description: "Greet someone and record the time"
inputs:
  DB_URL:
    description: "Connection URL for the Database"
    required: true
    default: "JDBC:<URL>"
  DB_PASSWORD:
    description: "Connection Password for the Database"
    required: true
    default: "PASSWORD"
  DB_USERNAME:
    description: "Connection Username for the Database"
    required: true
    default: "USERNAME"
  DB_FAMILY:
    description: "Provide the DB FAMILY name like - postgress, snowflake"
    required: true
    default: "DB_FAMILY"
  DB_CHANGELOGFILE:
    description: "Provide the changelog file path relative to github repo"
    required: false
    default: "changelog.sf.xml"
  DRY_RUN:
    description: "Mention if this is a Dry Run"
    required: false
    default: "Yes"

outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.DB_URL }}
    - ${{ inputs.DB_USERNAME }}
    - ${{ inputs.DB_PASSWORD}}
    - ${{ inputs.DB_FAMILY}}
    - ${{ inputs.DB_CHANGELOGFILE}}
    - ${{ inputs.DRY_RUN}}
